spring.application.name=backend

#Not giving my data 
spring.datasource.url=jdbc:postgresql://localhost:5432/prepmate
spring.datasource.password=your password
spring.datasource.username=postgres

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=Your key
jwt.expiration=86400000

ollama.url=http://localhost:11434/api/generate
ollama.model=gemma3:4b